<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="gdal_csharp">
      <HintPath>..\..\..\..\..\..\..\.nuget\packages\gdal\3.11.3\lib\netstandard2.0\gdal_csharp.dll</HintPath>
    </Reference>
    <Reference Include="ogr_csharp">
      <HintPath>..\..\..\..\..\..\..\.nuget\packages\gdal\3.11.3\lib\netstandard2.0\ogr_csharp.dll</HintPath>
    </Reference>
    <Reference Include="osr_csharp">
      <HintPath>..\..\..\..\..\..\..\.nuget\packages\gdal\3.11.3\lib\netstandard2.0\osr_csharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
