name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: HydrologicEngineeringCenter/dotnet-workflows/.github/workflows/release.yml@main
    with:
      dotnet-version: 8.0.x
      project-names: Nsi.Geospatial, Nsi.Geospatial.Io, Nsi.Geospatial.Reprojection
      nuget-source: https://nuget.pkg.github.com/USACE-NSI/index.json
    secrets:
      NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}